
export enum ModalType {
    CREATE_GUILD,
    CREATE_CHANNEL,
    CREATE_CATEGORY,
    SETTINGS,
    CHANNEL_SETTINGS,
    GUILD_SETTINGS,
    DELETE_CHANNEL,
    CREATE_INVITE,
    LEAVE_GUILD,
    ADD_ROLE_MEMBERS
}