
export enum ModalType {
    CREATE_GUILD,
    CREATE_CHANNEL,
    CREATE_CATEGORY,
    DELETE_CHANNEL,
    CREATE_INVITE,
    LEAVE_GUILD,
    ADD_ROLE_MEMBERS,
    REMOVE_PERMISSION_OVERWRITE,
    DELETE_ROLE
}